# Site settings
title: KernelCurry
email: info@kernelcurry.com
description: "Posts and project updates from Michael Ian Curry (Kernelcurry)"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kernelcurry.com" # the base hostname & protocol for your site
image: \img\global\main.jpg
twitter_username:  kernelcurry
github_username:   michaelcurry
linkedin_username: michaeliancurry
youtube_channel: "https://www.youtube.com/channel/UCb4ZxGv2-a3BP88hui0Udlw"

collections:
  posts:
    output: true
  projects:
    output: true
  podcasts:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: page
  -
    scope:
      path: blog
      type: posts
    values:
      layout: post
  -
    scope:
      path: projects
      type: projects
    values:
      layout: project

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]