# Site settings
title: KernelCurry
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Just another site
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kernelcurry.com" # the base hostname & protocol for your site
twitter_username:  kernelcurry
github_username:   michaelcurry
linkedin_username: michaeliancurry

# Build settings
markdown: redcarpet

# plugins
gems: ['jekyll-less', 'jekyll-sitemap', 'jekyll-redirect-from', 'jekyll-press']

# jekyll press to compress all of the things
jekyll-press:
  exclude: 'sitemap.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options