# Site settings
title: KernelCurry
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Just another site
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kernelcurry.com" # the base hostname & protocol for your site
twitter_username:  kernelcurry
github_username:   michaelcurry
linkedin_username: michaeliancurry

# Build settings
markdown: kramdown


# plugins
gems: ['jekyll-less']