baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "kernel"


[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    title = "Blog"
    url = "/blog"
    weight = 10

  [[menu.main]]
    identifier = "career"
    name = "Career"
    title = "Career"
    url = "/career"
    weight = 20

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    title = "Projects"
    url = "/projects"
    weight = 30