name: Build
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    # Job name is Greeting
    name: Build
    # This job runs on Linux
    runs-on: ubuntu-latest
    # Job Steps
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install -g gatsby-cli
      - run: pwd
      - run: ls -al