name: Deploy
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master

jobs:
  build:
    # Job name is Greeting
    name: Deploy
    # This job runs on Linux
    runs-on: ubuntu-latest
    # Job Steps
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Clone gh-pages to ../build
        run: git clone -b gh-pages git@github.com:kernelcurry/kernelcurry-site.git ../build
      - name: Nivigate to Build Directory
        run: cd ../build || exit 1
      - name: Git Pull
        run: git pull
      - name: list
        run: ls -al