name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
        with:
          ref: 'master'
          path: './master'
      - uses: actions/checkout@v2-beta
        with:
          ref: 'gh-pages'
          path: './gh-pages'
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Build Static Site
        run: |
          cd ./master || exit 1
          gatsby clean
          gatsby build
          cp CNAME ./public/CNAME
      - name: Clean & Update gh-pages
        run: |
          rm -rf ./gh-pages/*
          cp -R ./master/* ./gh-pages/
      - name: Deploy gh-pages
          run: |
            cd ./gh-pages || exit 1
            git add --all
            'git commit -m ":rocket: GH Actions - $(date -u)"'
            ls -al