name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
        with:
          ref: 'master'
          path: './master'
      - uses: actions/checkout@v2-beta
        with:
          ref: 'gh-pages'
          path: './gh-pages'
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: List Repo Directories
        run: |
          ls -al ./master
          ls -al ./gh-pages
      - name: tmp
        run: |
          cd ./gh-pages || exit 1
          pwd
          git pull
          ls -al