name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
        with:
          ref: 'master'
          path: './master'
      - uses: actions/checkout@v2-beta
        with:
          ref: 'gh-pages'
          path: './gh-pages'
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: list Master
        run: ls -al ./master
      - name: list gh-pages
        run: ls -al ./gh-pages
      - name: Nivigate to gh-pages Directory
        run: cd ./gh-pages || exit 1
      - name: pwd
        run: pwd
      - name: Git Pull
        run: cd ./gh-pages & /usr/bin/git pull
      - name: list
        run: ls -al