name: Deploy
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master

jobs:
  build:
    # Job name is Greeting
    name: Deploy
    # This job runs on Linux
    runs-on: ubuntu-latest
    # Job Steps
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v2-beta
        with:
          # The branch, tag or SHA to checkout.  When checking out the repository that
          # triggered a workflow, this defaults to the reference or SHA for that event.
          # Otherwise, defaults to `master`.
          ref: 'gh-pages'

          # Relative path under $GITHUB_WORKSPACE to place the repository
          path: '../build'
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Nivigate to Build Directory
        run: cd ../build || exit 1
      - name: Git Pull
        run: git pull
      - name: list
        run: ls -al